NAME           = clock
EXTRA_DEPS     = ../../lib/vdg.fs \
              ../../lib/screen.fs \
              ../../lib/rg-pixel.fs \
              ../../lib/datawrite.fs \
              ../../lib/font-art.fs \
              ../../lib/trig.fs \
              ../../lib/fujinet.fs
XROAR_EXTRA = -cart-rom ~/.xroar/roms/hdbdw3cc2.rom -cart-autorun -kbd-translate

include ../../make/demo.mk
