NAME           = colored-text
EXTRA_DEPS     = ../../lib/vdg.fs \
              ../../lib/bye.fs \
              ../../lib/rg-pixel.fs \
              ../../lib/font-art.fs \
              ../../lib/rg-text.fs
XROAR_EXTRA    = -tv-input cmp-br -kbd-translate

include ../../make/demo.mk
