#!/usr/bin/env python3
"""
gen-lib-metrics.py — produce build/lib-metrics.json for lib/README.md.

Builds a synthetic Forth program that INCLUDEs every lib/*.fs file in a
topological order derived from their `Requires:` headers, then runs
`fc.py --metrics-json` to compute per-word byte sizes and cycle costs
across the full library surface.

The resulting JSON feeds tools/gen-lib-readme.py, which adds Bytes /
Cycles / Notes columns to the auto-generated lib word table.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT       = Path(__file__).parent.parent
LIB_DIR    = ROOT / "lib"
BUILD_DIR  = ROOT / "build"
KERNEL_MAP = ROOT / "kernel" / "build" / "kernel.map"
STUB_FS    = BUILD_DIR / "lib-metrics.fs"
STUB_BIN   = BUILD_DIR / "lib-metrics.bin"
METRICS    = BUILD_DIR / "lib-metrics.json"
FC_PY      = ROOT / "tools" / "fc.py"

FS_REF_RE = re.compile(r"\b([\w-]+\.fs)\b")


def parse_header(path):
    """Pull `Requires:` lines from the leading \\-comment block."""
    requires = []
    current = None
    started = False
    for line in path.read_text().splitlines():
        s = line.rstrip()
        if not s:
            if started:
                break
            continue
        if not s.startswith("\\"):
            break
        started = True
        body = s[1:]
        if body.startswith(" "):
            body = body[1:]
        is_continuation = body.startswith((" ", "\t"))
        content = body.strip()
        low = content.lower()
        if low.startswith("requires:"):
            requires.append(content[9:].strip())
            current = "requires"
        elif is_continuation and current == "requires" and requires:
            requires[-1] += " " + content
        elif content:
            current = None
    return " ".join(requires)


def real_includes(path):
    """Return lib filenames mentioned by actual `INCLUDE foo.fs` lines (not comments)."""
    refs = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped.startswith("\\"):
            continue
        m = re.match(r"INCLUDE\s+(\S+)", stripped)
        if m:
            refs.append(m.group(1))
    return refs


def topo_sort(deps):
    """Kahn's algorithm. deps: {name: set(deps)}. Returns ordered list."""
    remaining = {n: set(d) for n, d in deps.items()}
    out = []
    while remaining:
        ready = sorted(n for n, d in remaining.items() if not d)
        if not ready:
            # Cycle — fall back to alphabetical order, drop deps to break it.
            ready = sorted(remaining)
        for n in ready:
            out.append(n)
            del remaining[n]
            for s in remaining.values():
                s.discard(n)
    return out


def build_stub():
    libs = sorted(p.name for p in LIB_DIR.glob("*.fs"))
    lib_set = set(libs)

    # Doc-level deps (from Requires: headers) ∪ real INCLUDEs in body.
    deps = {}
    body_includes = {}
    for name in libs:
        path = LIB_DIR / name
        doc_refs = set(FS_REF_RE.findall(parse_header(path))) & lib_set
        body_refs = set(real_includes(path)) & lib_set
        deps[name] = (doc_refs | body_refs) - {name}
        body_includes[name] = body_refs

    order = topo_sort(deps)

    # Skip libs that another (already-included) lib will pull in via real INCLUDE.
    # If A INCLUDEs B in its body, including both A and B at top level
    # re-tokenises B's definitions and inflates the work; deps on dict
    # overwrite would still work, but this keeps the stub minimal.
    pulled_in = set()
    final = []
    for name in order:
        if name in pulled_in:
            continue
        final.append(name)
        # Walk the include closure to mark transitively-pulled libs.
        stack = [name]
        while stack:
            n = stack.pop()
            for sub in body_includes.get(n, ()):
                if sub not in pulled_in:
                    pulled_in.add(sub)
                    stack.append(sub)

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    lines = [f"\\ Auto-generated by tools/gen-lib-metrics.py — do not edit.",
             f"\\ Compiles every lib/*.fs to derive per-word size + cycle metrics.",
             ""]
    for name in final:
        lines.append(f"INCLUDE {LIB_DIR / name}")
    lines += ["", ": main ;", "main", ""]
    STUB_FS.write_text("\n".join(lines))
    return final


def main():
    if not KERNEL_MAP.exists():
        sys.exit(f"gen-lib-metrics: {KERNEL_MAP} missing — run `make` in kernel/ first.")
    included = build_stub()
    cmd = [sys.executable, str(FC_PY), str(STUB_FS),
           "--kernel", str(KERNEL_MAP),
           "--output", str(STUB_BIN),
           "--metrics-json", str(METRICS)]
    print(f"gen-lib-metrics: including {len(included)} libs → {STUB_FS.relative_to(ROOT)}")
    result = subprocess.run(cmd, cwd=ROOT)
    if result.returncode != 0:
        sys.exit(result.returncode)

    # Strip the synthetic `main` word the stub adds so fc.py has something
    # to compile. It isn't a real lib word and would otherwise show up in
    # the README's "missing descriptions" list.
    data = json.loads(METRICS.read_text())
    if data.get("forth_words", {}).pop("main", None) is not None:
        METRICS.write_text(json.dumps(data, indent=2))


if __name__ == "__main__":
    main()
